In [1]:
from scipy.io import loadmat
import numpy as np
data = loadmat('sat-4-full.mat')

In [2]:
trainx = data['train_x']
trainy = data['train_y']

## Data Preprocessing

In [3]:
# The goal is to build a Data frame, which uses the image as unit. There are 784 pixels to describe each unit and four channels (red, green, blue and NIR components) to describe each pixel.

x=np.zeros(((40000,784,4))) 
w=0;
for l in range(0,40000):
    for i in range(0,28):
        for j in range(0,28):
            for k in range(0,4):
                x[l][w][k]=trainx[i][j][k][l]
            w=w+1
    w=0

In [4]:
x

array([[[104., 103.,  94., 133.],
        [114., 115., 106., 145.],
        [104., 110., 104., 138.],
        ...,
        [110., 104.,  95., 141.],
        [101., 103.,  92., 138.],
        [103., 110.,  99., 148.]],

       [[175., 149., 130., 146.],
        [169., 148., 130., 141.],
        [166., 139., 125., 133.],
        ...,
        [129., 122., 119., 132.],
        [137., 133., 121., 134.],
        [134., 128., 119., 132.]],

       [[113., 114., 105., 163.],
        [126., 131., 125., 176.],
        [119., 125., 119., 168.],
        ...,
        [132., 131., 129., 177.],
        [122., 126., 113., 172.],
        [130., 136., 131., 181.]],

       ...,

       [[198., 175., 149., 185.],
        [199., 180., 152., 185.],
        [201., 185., 154., 184.],
        ...,
        [204., 189., 165., 178.],
        [201., 187., 160., 177.],
        [200., 186., 159., 174.]],

       [[159., 139., 135., 191.],
        [160., 143., 135., 191.],
        [152., 135., 121., 182.],
        .

In [5]:
# transfer the RGB to HSV

import colorsys

v=np.zeros(((40000,784,4)))
w=0
for l in range(0,40000):
    for w in range(0,784):
        r=x[l][w][0]
        g=x[l][w][1]
        b=x[l][w][2]
        v[l][w][0]=colorsys.rgb_to_hsv(float(r)/float(255), float(g)/float(255), float(b)/float(255))[0]
        v[l][w][1]=colorsys.rgb_to_hsv(float(r)/float(255), float(g)/float(255), float(b)/float(255))[1]
        v[l][w][2]=colorsys.rgb_to_hsv(float(r)/float(255), float(g)/float(255), float(b)/float(255))[2]
        v[l][w][3]=x[l][w][3]

In [6]:
v

array([[[1.50000000e-01, 9.61538462e-02, 4.07843137e-01, 1.33000000e+02],
        [1.85185185e-01, 7.82608696e-02, 4.50980392e-01, 1.45000000e+02],
        [3.33333333e-01, 5.45454545e-02, 4.31372549e-01, 1.38000000e+02],
        ...,
        [1.00000000e-01, 1.36363636e-01, 4.31372549e-01, 1.41000000e+02],
        [1.96969697e-01, 1.06796117e-01, 4.03921569e-01, 1.38000000e+02],
        [2.72727273e-01, 1.00000000e-01, 4.31372549e-01, 1.48000000e+02]],

       [[7.03703704e-02, 2.57142857e-01, 6.86274510e-01, 1.46000000e+02],
        [7.69230769e-02, 2.30769231e-01, 6.62745098e-01, 1.41000000e+02],
        [5.69105691e-02, 2.46987952e-01, 6.50980392e-01, 1.33000000e+02],
        ...,
        [5.00000000e-02, 7.75193798e-02, 5.05882353e-01, 1.32000000e+02],
        [1.25000000e-01, 1.16788321e-01, 5.37254902e-01, 1.34000000e+02],
        [1.00000000e-01, 1.11940299e-01, 5.25490196e-01, 1.32000000e+02]],

       [[1.85185185e-01, 7.89473684e-02, 4.47058824e-01, 1.63000000e+02],
        

In [7]:
# transfer the original data set to a specific result of each image (0-barren land; 1-trees; 2-grassland; 3-none).
n=[]
for i in range(0,40000):
	for j in range(0,4):
		if trainy[j][i] != 0:
			n.append(j)

In [8]:
# calculate the mean value and standard deviation value of H, S and V separately in each image.

f=np.zeros((40000,9))
h=[]
s=[]
q=[]
m=[]
for l in range(0,40000):
    for w in range(0,784):
        h.append(v[l][w][0])
        s.append(v[l][w][1])
        q.append(v[l][w][2])
        m.append(v[l][w][3])
    f[l][0]=np.mean(h)
    f[l][1]=np.std(h)
    f[l][2]=np.mean(s)
    f[l][3]=np.std(s)
    f[l][4]=np.mean(q)
    f[l][5]=np.std(q)
    f[l][6]=np.mean(m)
    f[l][7]=np.std(m)
    f[l][8]=n[l]
    h=[]
    s=[]
    q=[]
    m=[]

In [9]:
f

array([[3.02351956e-01, 2.21281947e-01, 9.96103087e-02, ...,
        1.47093112e+02, 2.63363788e+01, 3.00000000e+00],
       [9.46482342e-02, 1.11863175e-01, 2.33110874e-01, ...,
        1.45095663e+02, 1.25512127e+01, 0.00000000e+00],
       [3.63837191e-01, 2.31356677e-01, 1.84357681e-01, ...,
        1.21929847e+02, 4.19700322e+01, 1.00000000e+00],
       ...,
       [1.08520789e-01, 9.44625144e-03, 2.09308626e-01, ...,
        1.75174745e+02, 4.00367496e+00, 0.00000000e+00],
       [7.82847186e-02, 1.05123143e-01, 1.74921212e-01, ...,
        1.98493622e+02, 1.48157032e+01, 0.00000000e+00],
       [1.42931924e-01, 6.20054950e-02, 1.47689768e-01, ...,
        1.90946429e+02, 7.03650739e+00, 2.00000000e+00]])

In [10]:
import pandas as pd

# create the pandas DataFrame
df = pd.DataFrame(f, columns = ['hue_mean', 'hue_std', 'saturation_mean', 'saturation_std', 'value_mean', 'value_std', 'NIR_mean', 'NIR_std', 'land_type'])
# print dataframe
df

hue_mean   hue_std  saturation_mean  saturation_std  value_mean  \
0      0.302352  0.221282         0.099610        0.065520    0.443607   
1      0.094648  0.111863         0.233111        0.046380    0.651581   
2      0.363837  0.231357         0.184358        0.144247    0.351676   
3      0.183581  0.226149         0.074254        0.066595    0.433193   
4      0.133382  0.113695         0.134510        0.056476    0.422039   
...         ...       ...              ...             ...         ...   
39995  0.119948  0.045974         0.189734        0.027545    0.695918   
39996  0.382745  0.274145         0.237039        0.126588    0.509514   
39997  0.108521  0.009446         0.209309        0.017396    0.785779   
39998  0.078285  0.105123         0.174921        0.081783    0.677706   
39999  0.142932  0.062005         0.147690        0.032552    0.581067   

       value_std    NIR_mean    NIR_std  land_type  
0       0.083579  147.093112  26.336379        3.0  
1       0.067891  145.095663  12.551213        0.0  
2       0.108887  121.929847  41.970032        1.0  
3       0.118928  127.181122  37.392367        3.0  
4       0.054106  135.001276   8.643964        2.0  
...          ...         ...        ...        ...  
39995   0.047970  167.354592   6.250859        0.0  
39996   0.068922  160.544643  26.694952        3.0  
39997   0.018004  175.174745   4.003675        0.0  
39998   0.097057  198.493622  14.815703        0.0  
39999   0.035305  190.946429   7.036507        2.0  

[40000 rows x 9 columns]

In [11]:
import pandas as pd
from sklearn import preprocessing

x = df.iloc[:,6:8].values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)

df.iloc[:,6:8] = x_scaled

# 参考：https://medium.com/dunder-data/selecting-subsets-of-data-in-pandas-6fcd0170be9c

In [12]:
df

hue_mean   hue_std  saturation_mean  saturation_std  value_mean  \
0      0.302352  0.221282         0.099610        0.065520    0.443607   
1      0.094648  0.111863         0.233111        0.046380    0.651581   
2      0.363837  0.231357         0.184358        0.144247    0.351676   
3      0.183581  0.226149         0.074254        0.066595    0.433193   
4      0.133382  0.113695         0.134510        0.056476    0.422039   
...         ...       ...              ...             ...         ...   
39995  0.119948  0.045974         0.189734        0.027545    0.695918   
39996  0.382745  0.274145         0.237039        0.126588    0.509514   
39997  0.108521  0.009446         0.209309        0.017396    0.785779   
39998  0.078285  0.105123         0.174921        0.081783    0.677706   
39999  0.142932  0.062005         0.147690        0.032552    0.581067   

       value_std  NIR_mean   NIR_std  land_type  
0       0.083579  0.590058  0.359279        3.0  
1       0.067891  0.581260  0.163114        0.0  
2       0.108887  0.479221  0.581749        1.0  
3       0.118928  0.502351  0.516608        3.0  
4       0.054106  0.536797  0.107514        2.0  
...          ...       ...       ...        ...  
39995   0.047970  0.679304  0.073459        0.0  
39996   0.068922  0.649308  0.364382        3.0  
39997   0.018004  0.713750  0.041481        0.0  
39998   0.097057  0.816463  0.195338        0.0  
39999   0.035305  0.783219  0.084639        2.0  

[40000 rows x 9 columns]

In [13]:
X=df.iloc[:,:8]
y=df.iloc[:,8]

In [14]:
# train the SVM 
from sklearn.svm import SVC
clf = SVC(kernel='rbf', C= 30, gamma= 16)
clf.fit(X,y)

SVC(C=30, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=16, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [15]:
import pickle 
  
# Save the trained model as a pickle string. 
pickle.dump(clf, open("model.dat", "wb")) 

# 参考： https://machinelearningmastery.com/save-gradient-boosting-models-xgboost-python/